apiVersion: apps/v1
kind: Deployment
metadata:
  name: secure-gitops-app
  namespace: secure-gitops
  labels:
    app: secure-gitops-app
spec:
  replicas: 3
  selector:
    matchLabels:
      app: secure-gitops-app
  template:
    metadata:
      labels:
        app: secure-gitops-app
      annotations:
        vault.hashicorp.com/agent-inject: "true"
        vault.hashicorp.com/role: "secure-gitops-role"
        vault.hashicorp.com/agent-inject-secret-app-config: "secret/data/secure-gitops"
        vault.hashicorp.com/agent-inject-template-app-config: |
          {{- with secret "secret/data/secure-gitops" -}}
          integration_status={{ .Data.data.integration_status }}
          {{- end }}
    spec:
      serviceAccountName: secure-gitops-vault
      containers:
        - name: secure-gitops-app
          image: secure-gitops-app:v2
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 80
          resources:
            requests:
              cpu: "50m"
              memory: "32Mi"
            limits:
              cpu: "100m"
              memory: "64Mi"
          readinessProbe:
            httpGet:
              path: /
              port: 80
            initialDelaySeconds: 3
            periodSeconds: 5
          livenessProbe:
            httpGet:
              path: /
              port: 80
            initialDelaySeconds: 10
            periodSeconds: 10