apiVersion: v1
kind: Service
metadata:
  name: secure-gitops-service
  namespace: secure-gitops
spec:
  type: NodePort
  selector:
    app: secure-gitops-app
  ports:
    - name: http
      protocol: TCP
      port: 80
      targetPort: 80
      nodePort: 30080